inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "db/**/*"

Metrics/MethodLength:
  Exclude:
    - "db/**/*"

Metrics/AbcSize:
  Exclude:
    - "db/**/*"
    - "spec/**/*_spec.rb"

