reasons:
  - name: Convenience
    explanation:  An allowance app makes it easy for parents to manage their children's allowances from their smartphones, without having to carry cash or remember to make payments manually
    image: hero.jpg

  - name: Tracking
    explanation: A kids' allowance app allows parents to track how much money their children receive and spend, helping them to monitor their kids' spending habits and teach them financial responsibility
    image: hero.jpg

  - name: Budgeting
    explanation: Parents can use an allowance app to set up a budget for their children, which can help kids learn how to manage money and make wise spending decisions
    image: hero.jpg

  - name: Teaching financial literacy
    explanation: An allowance app can be a useful tool for parents to teach their children about money management and financial literacy
    image: hero.jpg

  - name: Encouraging responsibility
    explanation: By using an allowance app, parents can encourage their children to take responsibility for their own spending and saving, which can help kids develop important life skills
    image: hero.jpg

  - name: Overall
    explanation: A kids' allowance app can be a useful tool for parents to help their children learn about money and develop good financial habits that will serve them well in the future
    image: hero.jpg
