name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@9669f3ee51dc3f4eda8447ab696b3ab19a90d14b
        with:
          ruby-version: '2.7.4'
          bundler-cache: true
      - name: Debug RAILS_MASTER_KEY
        run: echo 'RAILS_MASTER_KEY:' $RAILS_MASTER_KEY
      - name: Copy config
        run: cp config/database.yml.ci config/database.yml
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Rspec
        run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@9669f3ee51dc3f4eda8447ab696b3ab19a90d14b
        with:
          ruby-version: '2.7.4'
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
